version: "3"

services:
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db
    ports: 
      - "5432:5432"
    env_file:
      - ./.env

  django:
    build: ./backend
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py collectstatic --noinput && gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - node
  node:
    build: ./frontend
    command: bash -c "parcel watch bundles-src/index.js -d bundles --public-url='./'"
    volumes:
      - static_volume:/code/bundles
    ports:
      - 8080:8080
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/static
      - media_volume:/opt/media
    depends_on:
      - django
      
volumes:
  db_data:
  static_volume:
  media_volume:


