# Generated by Django 3.2 on 2022-06-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placelocation',
            name='category',
        ),
    ]
