# Generated by Django 3.2 on 2022-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_remove_placelocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
    ]
