# Generated by Django 3.2 on 2022-06-04 14:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20220603_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='count',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='номер телефона'),
        ),
    ]
