# Generated by Django 3.2 on 2022-06-06 12:46

from django.db import migrations


def add_price_field(apps, schema_editor):
    Purchase = apps.get_model('foodcartapp', 'Purchase')
    for purchase in Purchase.objects.all():
        purchase.price = purchase.product.price
        purchase.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_purchase_price'),
    ]

    operations = [
        migrations.RunPython(add_price_field),
    ]
