# Generated by Django 3.2 on 2022-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220609_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Онлайн')], db_index=True, default='CASH', max_length=5, verbose_name='метод оплаты'),
            preserve_default=False,
        ),
    ]
