# Generated by Django 3.2 on 2022-06-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UN', 'Необработан'), ('P', 'Готовится'), ('OTW', 'В пути'), ('D', 'Завершён')], db_index=True, default='UN', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.product', verbose_name='блюдо'),
        ),
    ]
