# Generated by Django 3.2 on 2022-11-13 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='номер телефона')),
                ('firstname', models.CharField(max_length=50, verbose_name='имя покупателя')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='фамилия покупателя')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='адрес')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата и время заказа')),
                ('called_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время потверждения')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время доставки')),
                ('status', models.CharField(choices=[('UN', 'Необработан'), ('P', 'Готовится'), ('OTW', 'В пути'), ('D', 'Завершён')], db_index=True, default='UN', max_length=10, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('payment', models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Онлайн')], db_index=True, max_length=5, verbose_name='метод оплаты')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant', verbose_name='готовящий ресторан')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='orders.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='products.product', verbose_name='блюдо')),
            ],
            options={
                'verbose_name': 'покупка',
                'verbose_name_plural': 'покупки',
            },
        ),
    ]
